#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Uni-Agent single-node smoke test
#
# Minimal end-to-end test that exercises the full agentic RL loop
#   rollout (ReAct + local sandbox + tools) -> reward -> policy update
# on ONE node, with as little setup as possible. It is intentionally NOT a
# production recipe: it only needs to finish a couple of steps and print
# rollout / reward / policy-update numbers so you can validate the pipeline.
#
# Requirements:
#   - verl + uni_agent installed in the current python env
#   - a small HF model (default: Qwen3-1.7B) that supports the tool-call
#     format set in TOOL_PARSER
#   - NPU: a sourced CANN environment (Ascend)
#
# Usage (launch from the repository root so both `verl/` and `uni_agent/`
# are importable):
#   DEVICE=npu  NGPUS_PER_NODE=8  bash examples/quickstart/training/run_agentic_smoke.sh
#   DEVICE=cuda NGPUS_PER_NODE=1  MODEL_PATH=Qwen/Qwen2.5-1.5B-Instruct \
#       bash examples/quickstart/training/run_agentic_smoke.sh
#
# The dummy math dataset is auto-generated by gen_dummy_math_data.py when
# DATA_DIR is empty.
# ============================================================================

# Resolve this script's own directory so paths stay correct regardless of cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- device & topology ------------------------------------------------------
DEVICE=${DEVICE:-npu}                     # cuda | npu
NNODES=${NNODES:-1}
NGPUS_PER_NODE=${NGPUS_PER_NODE:-8}

# ---- model & agent framework ------------------------------------------------
MODEL_PATH=${MODEL_PATH:-"${HOME}/models/Qwen3-1.7B"}
MODEL_NAME=${MODEL_NAME:-"$(basename "${MODEL_PATH}")"}
TOOL_PARSER=${TOOL_PARSER:-hermes}        # gateway tool-call parser; MUST match the model chat template
TASK_CONFIG=${TASK_CONFIG:-"${SCRIPT_DIR}/task_config_math.yaml"}
GATEWAY_COUNT=${GATEWAY_COUNT:-${NGPUS_PER_NODE}}
CONCURRENCY=${CONCURRENCY:-${NGPUS_PER_NODE}}
AGENT_WORKERS=${AGENT_WORKERS:-${NGPUS_PER_NODE}}
RAY_ADDR=${RAY_ADDR:-}                    # optional: existing Ray cluster address

# ---- data (auto-generated if missing) ---------------------------------------
DATA_DIR=${DATA_DIR:-"${HOME}/verl/data"}
TRAIN_FILE=${TRAIN_FILE:-"${DATA_DIR}/train.parquet"}
VAL_FILE=${VAL_FILE:-"${DATA_DIR}/val.parquet"}
GEN_SCRIPT=${GEN_SCRIPT:-"${SCRIPT_DIR}/gen_dummy_math_data.py"}

# ---- batching (tuned so the smoke test finishes in a few steps) -------------
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-4}
N_RESP=${N_RESP:-4}
PPO_MINI_BATCH_SIZE=${PPO_MINI_BATCH_SIZE:-2}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-1024}
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-2048}
TP=${TP:-1}                               # vLLM tensor parallel (rollout)
LR=${LR:-1e-6}
SAVE_FREQ=${SAVE_FREQ:-20}

# ---- output dirs -------------------------------------------------------------
PROJECT_NAME=${PROJECT_NAME:-"UniAgent-smoke"}
EXP_NAME=${EXP_NAME:-"$(date +%Y%m%d%H%M)_exp"}
CKPTS_DIR=${CKPTS_DIR:-"${HOME}/verl/ckpts/${PROJECT_NAME}/${EXP_NAME}"}
AGENT_LOG_DIR=${AGENT_LOG_DIR:-"${HOME}/verl/logs/${PROJECT_NAME}/${EXP_NAME}"}
mkdir -p "${CKPTS_DIR}" "${AGENT_LOG_DIR}"

# ---- device setup ------------------------------------------------------------
if [[ "${DEVICE}" == "npu" ]]; then
    # Ascend NPU: source CANN (paths depend on your install) and put torch_npu on LD_LIBRARY_PATH.
    CANN_SET_ENV=${CANN_SET_ENV:-"${HOME}/miniconda3/envs/uni-agent/Ascend/cann/set_env.sh"}
    ATB_SET_ENV=${ATB_SET_ENV:-"${HOME}/miniconda3/envs/uni-agent/Ascend/nnal/atb/set_env.sh"}
    source "${CANN_SET_ENV}" 2>/dev/null || true
    source "${ATB_SET_ENV}" 2>/dev/null || true
    export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib/python3.11/site-packages/torch/lib:${CONDA_PREFIX}/lib/python3.11/site-packages/torch_npu/lib:${LD_LIBRARY_PATH:-}"
    DEVICE_FLAG="trainer.device=npu"
else
    DEVICE_FLAG="trainer.device=cuda"
fi

# ---- auto-generate the dummy dataset when needed -----------------------------
if [[ ! -f "${TRAIN_FILE}" || ! -f "${VAL_FILE}" ]]; then
    echo "[run_agentic_smoke] generating dummy math dataset -> ${DATA_DIR}"
    python3 "${GEN_SCRIPT}" --data_dir "${DATA_DIR}"
fi

echo "=============================================="
echo "  Uni-Agent smoke test (${DEVICE}, ${NNODES} node x ${NGPUS_PER_NODE})"
echo "  Model       : ${MODEL_PATH}"
echo "  Train data  : ${TRAIN_FILE}"
echo "  Task config : ${TASK_CONFIG}"
echo "  Agent log   : ${AGENT_LOG_DIR}"
echo "=============================================="

# ---- run ---------------------------------------------------------------------
CMD=(python3 -m verl.trainer.main_ppo
    trainer.use_v1=True
    trainer.v1.trainer_mode=colocate_async
    trainer.v1.colocate_async.num_warmup_batches=1
    transfer_queue.enable=True
    data.train_files="${TRAIN_FILE}"
    data.val_files="${VAL_FILE}"
    data.prompt_key=prompt
    data.truncation=left
    data.max_prompt_length=${MAX_PROMPT_LENGTH}
    data.max_response_length=${MAX_RESPONSE_LENGTH}
    data.train_batch_size=${TRAIN_BATCH_SIZE}
    data.return_raw_chat=True
    actor_rollout_ref.rollout.n=${N_RESP}
    algorithm.adv_estimator=grpo
    algorithm.use_kl_in_reward=False
    algorithm.kl_ctrl.kl_coef=0.0
    actor_rollout_ref.actor.use_kl_loss=False
    actor_rollout_ref.actor.kl_loss_coef=0.0
    actor_rollout_ref.actor.clip_ratio_low=0.2
    actor_rollout_ref.actor.clip_ratio_high=0.28
    actor_rollout_ref.actor.clip_ratio_c=10.0
    actor_rollout_ref.actor.use_torch_compile=False
    actor_rollout_ref.ref.use_torch_compile=False
    actor_rollout_ref.actor.fsdp_config.use_torch_compile=False
    actor_rollout_ref.ref.fsdp_config.use_torch_compile=False
    actor_rollout_ref.model.use_remove_padding=True
    actor_rollout_ref.actor.use_dynamic_bsz=True
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=1536
    actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=1536
    actor_rollout_ref.rollout.log_prob_max_token_len_per_gpu=1536
    actor_rollout_ref.rollout.name=vllm
    actor_rollout_ref.rollout.mode=async
    actor_rollout_ref.hybrid_engine=True
    actor_rollout_ref.rollout.checkpoint_engine.update_weights_bucket_megabytes=4096
    actor_rollout_ref.model.path="${MODEL_PATH}"
    +actor_rollout_ref.model.override_config.attention_dropout=0.
    +actor_rollout_ref.model.override_config.embd_pdrop=0.
    +actor_rollout_ref.model.override_config.resid_pdrop=0.
    actor_rollout_ref.model.enable_gradient_checkpointing=True
    actor_rollout_ref.actor.optim.lr=${LR}
    actor_rollout_ref.actor.optim.lr_warmup_steps=10
    actor_rollout_ref.actor.optim.weight_decay=0.1
    actor_rollout_ref.actor.ppo_mini_batch_size=${PPO_MINI_BATCH_SIZE}
    actor_rollout_ref.actor.fsdp_config.param_offload=True
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1
    actor_rollout_ref.ref.fsdp_config.param_offload=True
    actor_rollout_ref.ref.fsdp_config.fsdp_size=-1
    actor_rollout_ref.actor.entropy_coeff=0
    actor_rollout_ref.actor.grad_clip=1.0
    actor_rollout_ref.actor.loss_agg_mode=token-mean
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1
    actor_rollout_ref.rollout.gpu_memory_utilization=0.65
    actor_rollout_ref.rollout.tensor_model_parallel_size=${TP}
    actor_rollout_ref.rollout.enable_chunked_prefill=True
    actor_rollout_ref.rollout.max_num_batched_tokens=2048
    actor_rollout_ref.rollout.max_model_len=2048
    actor_rollout_ref.rollout.free_cache_engine=True
    actor_rollout_ref.rollout.enforce_eager=False
    actor_rollout_ref.rollout.temperature=1.0
    actor_rollout_ref.rollout.top_p=1.0
    actor_rollout_ref.rollout.top_k=-1
    actor_rollout_ref.rollout.val_kwargs.temperature=1.0
    actor_rollout_ref.rollout.val_kwargs.top_p=1.0
    actor_rollout_ref.rollout.val_kwargs.top_k=-1
    actor_rollout_ref.rollout.val_kwargs.do_sample=True
    actor_rollout_ref.rollout.val_kwargs.n=1
    actor_rollout_ref.nccl_timeout=9600
    reward.reward_manager.name=dapo
    +reward.reward_kwargs.max_resp_len=${MAX_RESPONSE_LENGTH}
    trainer.logger="['console']"
    trainer.project_name="${PROJECT_NAME}"
    trainer.experiment_name="${EXP_NAME}"
    trainer.n_gpus_per_node=${NGPUS_PER_NODE}
    trainer.nnodes=${NNODES}
    trainer.val_before_train=False
    trainer.test_freq=-1
    trainer.save_freq=${SAVE_FREQ}
    trainer.total_epochs=${TOTAL_EPOCHS}
    trainer.default_local_dir="${CKPTS_DIR}"
    trainer.resume_mode=auto
    ${DEVICE_FLAG}
    actor_rollout_ref.rollout.multi_turn.enable=True
    actor_rollout_ref.rollout.multi_turn.max_parallel_calls=1
    ++actor_rollout_ref.rollout.multi_turn.format=${TOOL_PARSER}
    actor_rollout_ref.rollout.agent.num_workers=${AGENT_WORKERS}
    ++actor_rollout_ref.rollout.agent.agent_loop_manager_class=uni_agent.framework.entry.AgentFrameworkRolloutAdapter
    ++actor_rollout_ref.rollout.custom.agent_framework.gateway_count=${GATEWAY_COUNT}
    ++actor_rollout_ref.rollout.custom.agent_framework.log_dir=${AGENT_LOG_DIR}
    ++actor_rollout_ref.rollout.custom.agent_framework.agent_runners.task.runner_fqn=uni_agent.framework.task_runner.run_task
    ++actor_rollout_ref.rollout.custom.agent_framework.agent_runners.task.dispatch_mode=ray_task
    ++actor_rollout_ref.rollout.custom.agent_framework.agent_runners.task.max_concurrent_sessions=${CONCURRENCY}
    ++actor_rollout_ref.rollout.custom.agent_framework.agent_runners.task.runner_kwargs.task_config_path=${TASK_CONFIG}
    ++actor_rollout_ref.rollout.custom.agent_framework.agent_runners.task.runner_kwargs.model_name=${MODEL_NAME}
    ++actor_rollout_ref.rollout.custom.agent_framework.agent_runners.task.runner_kwargs.report_reward=True
    ++actor_rollout_ref.rollout.custom.agent_framework.use_reward_loop_worker=False
)
if [[ -n "${RAY_ADDR}" ]]; then
    CMD+=(+ray_kwargs.ray_init.address="${RAY_ADDR}")
fi

"${CMD[@]}" 2>&1 | tee "${HOME}/verl/logs/${PROJECT_NAME}_${EXP_NAME}.log"
